version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: bolttech-nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/sites/api.bolttech.dev.conf:/etc/nginx/conf.d/api.bolttech.dev.conf
    networks:
      code-network:
        aliases:
          - api.bolttech.dev
  php:
    image: bolttech:php-latest
    container_name: bolttech-php
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_SESSION: "PHPSTORM"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/app
    user: ${USER}:${USER}
    volumes:
      - ./app:/var/www/app
      - $HOME/.ssh:/home/${USER}/.ssh
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
